language: node_js
sudo: false
before_install:
  - "export CODECLIMATE_REPO_TOKEN=10ab414b4658d48f2ba9d476d1f2cd474c8d6a9cda30cf92fbd446f22d732d8f"
install:
  - "npm install"
script:
  - "npm run travis"
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
cache:
  directories:
    - 'node_modules'
